Ndlano/issues#313 save old node
NDLANO/listing-api pull request #11
Opened 2017-04-28 13:10 UTC by narhen

2017-05-02 09:34 UTC, tanjag commented
Men, hvorfor ikke bare oppdatere det coveret som finnes fra før versus å avvise den med ```CoverAlreadyExistsException``` - da har man mulighet for at å få med seg endringer i en mellomfase.

2017-05-02 10:48 UTC, tanjag requested changes

2017-05-02 10:48 UTC, tanjag commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -      writeService.newCover(extract[NewCover](request.body))
Hvorfor er endepunktet fjerna?

2017-05-02 10:48 UTC, tanjag commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -    put("/updatecover/:coverid") {
Hvorfor er endepunktet fjerna?

2017-05-02 17:05 UTC, narhen commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -    put("/updatecover/:coverid") {
Fordi det ikke er i bruk noen steder. Importeren bruker endepunktene i `ListingController` i stedet

2017-05-02 17:05 UTC, narhen commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -      writeService.newCover(extract[NewCover](request.body))
Fordi det ikke er i bruk noen steder. Importeren bruker endepunktene i `ListingController` i stedet

2017-05-02 17:13 UTC, narhen commented
`CoverAlreadyExistsException` kastes dersom man prøver å `POST`e  et *nytt* cover med en referanse til en artikkel på gamle-ndla som allerede er importert. Hvis det er slik at coveret allerede er importert og man vil oppdatere kortet burde ikke `POST` endepunktet brukes, men `PUT`.

Import-rutinen i deploy er basically slik:
1. post nytt cover
2. hvis "cover already exists" bruk artikkel-id feltet fra feilmeldingen i en put-request for å oppdatere eksisterende
3. oppdater resten av oversettelsene for coveret.

2017-05-03 07:20 UTC, tanjag commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -    put("/updatecover/:coverid") {
Da er errejogreit.

2017-05-03 07:20 UTC, tanjag commented on src/main/scala/no/ndla/listingapi/controller/InternController.scala
> -      writeService.newCover(extract[NewCover](request.body))
Da er errejogreit.

2017-05-03 07:21 UTC, tanjag approved these changes

2017-05-03 07:22 UTC, tanjag commented
Bra da funker det jo akkurat som håpet, jeg ble bare trown off da jeg trodde endepunktene hadde blitt fjerna.

2017-05-03 14:05 UTC, merged